In [1]:
import os
import pandas as pd

from src.constants import *

In [2]:
with open(os.path.join(ARTICLES_PATH, "33555423", "entities.csv"), "r") as f:
    entities_df = pd.read_csv(f).drop('Unnamed: 0', axis=1)

In [5]:
entities_df

,Word,Type,CUI,Document,StartChar,EndChar,StartWord,EndWord,Sentence
0,anastomotic leakage,DISO,C0919691,33555423,0,19,0,1,0
1,AL,DISO,C0919691,33555423,21,23,2,2,0
2,complication,DISO,C0009566,33555423,56,69,9,9,0
3,colorectal surgery,OCCU,C0009369,33555423,76,94,11,12,0
4,affect,CONC,C0392760,33555423,96,105,13,13,0
...,...,...,...,...,...,...,...,...,...
1328,level of anastomosis,PROC,C0677554,33555423,21794,21814,3686,3688,243
1329,height of anastomosis,PROC,C0677554,33555423,21816,21837,3689,3691,243
1330,compare,ENTITY,UNDEF,33555423,21842,21851,3693,3693,243
1331,hand-sewn,ENTITY,UNDEF,33555423,21852,21861,3694,3694,243
1332,staple anastomosis,ENTITY,UNDEF,33555423,21866,21885,3696,3697,243

In [7]:
len(entities_df["Type"].value_counts())

21

In [8]:
entities_df["Type"].value_counts()

CONC        486
CARDINAL    149
DISO        141
PROC        134
ENTITY      103
PERCENT      92
CHEM         45
LIVB         40
ORG          24
ACTI         21
OBJC         17
OCCU         17
DATE         14
ANAT         13
PHEN         10
PHYS          9
GEOG          7
PERSON        5
PRODUCT       4
ORDINAL       1
NORP          1
Name: Type, dtype: int64